(()=>{
'use strict';
const VER='v3.15', STRATEGY_CHECKED='2026-09-21';
const LS_PATROL='hallscan_patrol_v1', LS_MEMO='hallscan_found_memos_v1';
const LS_RATE_VIS='hallscan_rate_visibility_v2';
const NORMAL_FAV_KEY='okhotsk_favorites_v2';
const PHOTO_GUIDES=[
 {re:/モンキーターンV/,title:'モンキーターンV',photos:[
  {src:'./hallscan-monkey-main.webp',caption:'メイン液晶。右上のpt表示を確認。',markers:[{x:88,y:14,t:'pt'}]},
  {src:'./hallscan-monkey-side.webp',caption:'サブ液晶。メニュー・履歴などを確認する位置。',markers:[{x:52,y:20,t:'サブ液晶'}]}
 ]},
 {re:/戦国乙女4/,title:'戦国乙女4',photos:[
  {src:'./hallscan-otome-main.webp',caption:'筐体正面。左側G数と右側サブ表示の位置を把握。',markers:[{x:9,y:59,t:'G数'},{x:90,y:58,t:'サブ'}]},
  {src:'./hallscan-otome-side.webp',caption:'右側サブ表示のアップ。数値を確認する場所。',markers:[{x:56,y:27,t:'ここ'}]}
 ]}
];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});
function daysSince(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(date||'')))return null;const a=new Date(date+'T00:00:00+09:00'),b=new Date(today()+'T00:00:00+09:00');return Math.max(0,Math.round((b-a)/86400000))}
function freshnessText(date,prefix='確認'){const d=String(date||'—'),n=daysSince(d);if(n===null)return `${prefix} ${d}`;const short=d.slice(5).replace('-','/'),age=n===0?'今日':`${n}日前`;return `${prefix} ${short}・${age}${n>=7?'・要再確認':''}`}
function freshnessClass(date){const n=daysSince(date);return n!==null&&n>=7?' hs-stale':''}
const FULLRATE=()=>window.HALLSCAN_FULLRATE||{};
const STRATEGY=()=>window.HALLSCAN_MACHINE_STRATEGY||{strategies:{},aliases:{},checked:STRATEGY_CHECKED};
function normLite(s){return String(s||'').normalize('NFKC').toLowerCase().replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60)).replace(/[\s\u3000・･·.。,:：;；!！?？'"“”‘’()（）\[\]【】「」『』<>＜＞\-‐‑‒–—―ー_\/\\~〜～]+/g,'')}
let hsStrategyIndexDb=null,hsStrategyIndex=null,hsStrategyAliasIndex=null;
function strategyIndexes(db){if(hsStrategyIndexDb===db&&hsStrategyIndex&&hsStrategyAliasIndex)return{idx:hsStrategyIndex,alias:hsStrategyAliasIndex};const idx={},alias={};for(const [rawKey,v] of Object.entries(db.strategies||{})){idx[normLite(rawKey)]=v;if(v?.name)idx[normLite(v.name)]=v}for(const [rawAlias,rawTarget] of Object.entries(db.aliases||{})){const v=(db.strategies||{})[rawTarget]||idx[normLite(rawTarget)];if(v)alias[normLite(rawAlias)]=v}hsStrategyIndexDb=db;hsStrategyIndex=idx;hsStrategyAliasIndex=alias;return{idx,alias}}
function strategyFor(name){const db=STRATEGY(),k=normLite(name),{idx,alias}=strategyIndexes(db);return (db.strategies||{})[k]||alias[k]||idx[k]||{name,type:'review',edge:false,check:'未監査',target:'未監査。G数だけで座らない。',ceiling:'未監査',short:'未監査',stop:'未監査のため見送り',note:'機種固有条件を確認できるまで推測しない。',source:'',checked:'—',basis:'fallback'};}
function statusInfo(s){switch(s?.type){case'edge':return{label:'期待値候補',cls:'edge'};case'yutime':return{label:'遊タイム',cls:'yutime'};case'setting':return{label:'設定/技術',cls:'setting'};case'no-g':return{label:'G数狙いなし',cls:'nog'};default:return{label:'未監査',cls:'review'}}}
function beginnerStrategyText(v){return String(v??'').replace(/等価・持ちメダル(?=\s*\d)/g,'交換ロスなし／持ちメダル：').replace(/等価交換(?=\s*\d)/g,'交換ロスなし：').replace(/等価(?=\s*\d)/g,'交換ロスなし：').replace(/5\.6枚現金(?=\s*\d)/g,'56枚=1000円交換・現金投資：').replace(/5\.6枚交換(?=\s*\d)/g,'56枚=1000円交換：').replace(/5\.6枚(?=\s*\d)/g,'56枚=1000円交換：').replaceAll('等価・持ちメダル','交換ロスなし／持ちメダル').replaceAll('等価交換','交換ロスなし').replaceAll('等価','交換ロスなし').replaceAll('5.6枚現金','56枚交換・現金投資').replaceAll('5.6枚交換','56枚交換').replaceAll('5.6枚','56枚交換')}
function targetForDisplay(s){const t=String(s?.target||'未監査');const out=s?.edge&&!/\d/.test(t)?`固定相談ライン未設定｜${t} 最新解析で期待値を再確認。`:t;return beginnerStrategyText(out)}
function storeTargetForDisplay(s,d,kind){const base=targetForDisplay(s);const p=d?.slotExchangeProfile;if(kind!=='slot'||!p||p.displayBasis!=='nonEqual56')return base;if(!/56枚=1000円交換/.test(base))return base;const exact56=Number(p.exchangePiecesPer1000)===56;return base.replaceAll('交換ロスなし／持ちメダル','参考（交換ロスなし／持ちメダル）').replaceAll('交換ロスなし','参考（交換ロスなし）').replaceAll('56枚=1000円交換・現金投資',exact56?'この店で使う暫定基準（現金投資）':'この店で使う暫定基準（現金投資・安全側）').replaceAll('56枚=1000円交換',exact56?'この店で使う暫定基準':'この店で使う暫定基準（安全側）')}
function storeExchangeNote(d){const s=d?.slotExchangeProfile,p=d?.pachiExchangeProfile,parts=[];if(s)parts.push(`20スロ：${s.lend}／${s.exchange}。${s.displayNote||''}`);if(p)parts.push(`4パチ：${p.exchange}。`);return parts.join(' ')}
function sourceNeedsWeb(s){return s?.sourceQuality==='needs-web'}
function sourceCaution(s){return sourceNeedsWeb(s)?'<div class="hs-guideText hs-cautionbox"><b>要Web再確認</b><br>P-WORLD店舗ページは設置確認用です。このカードの攻略条件は、A/B/C/D判定時に最新解析で再確認してください。</div>':''}
function getGuide(name){return PHOTO_GUIDES.find(x=>x.re.test(name||''));}
function storeName(){return document.querySelector('header h1')?.textContent.trim()||document.title.replace(/\s*[｜|].*$/,'');}
function getMemos(){try{return JSON.parse(localStorage.getItem(LS_MEMO)||'[]').filter(x=>x&&x.date===today())}catch(e){return[]}}
function saveMemos(a){try{localStorage.setItem(LS_MEMO,JSON.stringify(a))}catch(e){}}
function modal(){let m=document.getElementById('hsModal');if(m)return m;m=document.createElement('div');m.id='hsModal';m.className='hs-modal';m.innerHTML='<section class="hs-sheet" role="dialog" aria-modal="true"><div class="hs-sheethead"><strong id="hsModalTitle"></strong><button class="hs-close" type="button" aria-label="閉じる">×</button></div><div id="hsModalBody"></div></section>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('.hs-close'))m.classList.remove('open')});return m}
function openModal(title,html){const m=modal();m.querySelector('#hsModalTitle').textContent=title;m.querySelector('#hsModalBody').innerHTML=html;m.classList.add('open');return m}
function guideHtml(g){return `<div class="hs-guideText">写真は実際のホールで撮影した見え方です。数値の意味は機種カードの「まず見る」「相談ライン」と合わせて確認してください。</div><div class="hs-photos">${g.photos.map(p=>`<figure class="hs-photo"><img src="${p.src}" alt="${esc(g.title)}の確認場所" loading="eager">${(p.markers||[]).map(m=>`<span class="hs-marker" style="left:${m.x}%;top:${m.y}%">${esc(m.t)}</span>`).join('')}<figcaption class="hs-guideText" style="margin:0;border-radius:0">${esc(p.caption)}</figcaption></figure>`).join('')}</div>`}
function openGuide(name){const g=getGuide(name);if(!g)return;openModal('見る場所｜'+g.title,guideHtml(g))}
function openDecision(name,check,target,eligible=true,needsWeb=false){const lead=eligible?'相談ラインを満たしても着席確定ではありません。':'この分類はG数だけで着席判断しません。',src=needsWeb?'<div class="hs-guideText hs-cautionbox"><b>要Web再確認</b><br>攻略条件の参照元が設置確認ページのため、着席判断前に最新解析を再確認します。</div>':'';const m=openModal('その場判定｜'+name,`<div class="hs-guideText"><b>① まず見る</b><br>${esc(check||'機種カードの「まず見る」を確認')}</div><div class="hs-guideText"><b>② 相談ライン</b><br>${esc(target||'機種カードの条件を確認')}</div>${src}<div class="hs-guideText hs-cautionbox">${esc(lead)} 最終判断はChatGPTへ状態を送り、A/B/C/Dで確認してください。<b>Aだけ着席可</b>です。</div><div class="hs-decisionButtons"><button data-v="yes">条件を満たす</button><button data-v="no">満たさない</button><button data-v="unknown">判別できない</button></div><div id="hsDecisionResult" class="hs-result">上の条件と実機の状態を照合してください。</div>`);m.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const r=m.querySelector('#hsDecisionResult');if(!eligible){r.textContent='G数ハイエナ判定の対象外です。設定・回転率など別の根拠がなければ見送ります。';return}r.textContent=b.dataset.v==='yes'?'相談候補：まだ着席不可。機種名・現在G/pt/スルー等をChatGPTへ送り、A/B/C/D判定を受けてください。':b.dataset.v==='no'?'見送り：現在は相談ラインを満たしていません。':'見送り：重要条件を判別できない状態で有利側に推測しません。';});}
function openMemoForm(name){const m=openModal('見つけた台をメモ',`<form class="hs-form" id="hsMemoForm"><label>機種<input name="machine" value="${esc(name)}" readonly></label><label>台番号<input name="number" inputmode="numeric" placeholder="例 336"></label><label>現在G・ptなど<input name="state" placeholder="例 510G / 288pt"></label><label>ひとこと<textarea name="note" placeholder="例 CZ3スルー、あとで再確認"></textarea></label><button class="hs-primary" type="submit">今日の候補に保存</button></form>`);m.querySelector('#hsMemoForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),a=getMemos();a.unshift({id:Date.now(),date:today(),store:storeName(),page:location.pathname.split('/').pop(),machine:f.get('machine'),number:f.get('number'),state:f.get('state'),note:f.get('note')});saveMemos(a);m.classList.remove('open');updateMemoFab();};}
function openMemoList(){const a=getMemos(),html=a.length?`<div class="hs-memo-list">${a.map(x=>`<div class="hs-memo-item"><strong>${esc(x.machine)}${x.number?'｜台 '+esc(x.number):''}</strong><small>${esc(x.store)}${x.state?'｜'+esc(x.state):''}${x.note?'<br>'+esc(x.note):''}</small><button type="button" data-del="${x.id}">削除</button></div>`).join('')}</div><button class="hs-toolbtn" style="margin-top:12px" id="hsClearMemos">今日のメモをすべて削除</button>`:'<div class="hs-empty">今日保存した台はありません。</div>';const m=openModal('今日の候補',html);m.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{saveMemos(getMemos().filter(x=>String(x.id)!==b.dataset.del));openMemoList();updateMemoFab()});const c=m.querySelector('#hsClearMemos');if(c)c.onclick=()=>{saveMemos([]);openMemoList();updateMemoFab()};}
function updateMemoFab(){let b=document.getElementById('hsMemoFab');if(!b){b=document.createElement('button');b.id='hsMemoFab';b.className='hs-memo-fab';b.type='button';b.onclick=openMemoList;b.innerHTML='候補メモ <b>0</b>';document.body.appendChild(b)}const n=getMemos().length;b.querySelector('b').textContent=n;b.hidden=n===0;b.classList.toggle('has-items',n>0);}
function setPatrol(on){document.body.classList.toggle('hs-patrol',on);try{localStorage.setItem(LS_PATROL,on?'1':'0')}catch(e){}document.querySelectorAll('.hs-patrol-toggle').forEach(b=>{b.classList.toggle('on',on);b.setAttribute('aria-pressed',String(on));b.textContent=on?'巡回モード ON':'巡回モード'})}
function addPatrolToggle(){const target=document.querySelector('header')||document.querySelector('.v21-search-head .inner');if(!target||target.querySelector('.hs-patrol-toggle'))return;const wrap=document.createElement('div');wrap.className='hs-tools';wrap.innerHTML='<button type="button" class="hs-toolbtn hs-patrol-toggle">巡回モード</button>';target.appendChild(wrap);wrap.querySelector('button').onclick=()=>setPatrol(!document.body.classList.contains('hs-patrol'));let on=false;try{on=localStorage.getItem(LS_PATROL)==='1'}catch(e){}setPatrol(on)}
function machineData(name){try{if(typeof data!=='undefined'&&Array.isArray(data))return data.find(x=>x.name===name)||{};}catch(e){}return{}}
function replaceConsultationLabels(root=document.body){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>{const p=n.parentElement;if(!p||/^(SCRIPT|STYLE|TEXTAREA)$/.test(p.tagName))return NodeFilter.FILTER_REJECT;return n.nodeValue.includes('座る目安')?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{n.nodeValue=n.nodeValue.replaceAll('座る目安','相談ライン')});}
function decorateCards(){document.querySelectorAll('.card').forEach(card=>{if(card.dataset.hs315)return;const name=card.querySelector('.name')?.textContent.trim();if(!name)return;card.dataset.hs315='1';const d=machineData(name);const actions=document.createElement('div');actions.className='hs-card-actions';const g=getGuide(name);actions.innerHTML=`<span class="hs-checked${freshnessClass('2026-09-18')}">${esc(freshnessText('2026-09-18','低貸確認'))}</span>${g?'<button class="hs-toolbtn hs-photo-btn" type="button">📷 見る場所</button>':''}<button class="hs-toolbtn hs-judge-btn" type="button">A/B/C/D判定</button><button class="hs-toolbtn hs-memo-btn" type="button">＋台メモ</button>`;(card.querySelector('.targetline')||card.querySelector('.quick')||card.querySelector('.head')).after(actions);if(g)actions.querySelector('.hs-photo-btn').onclick=e=>{e.stopPropagation();openGuide(name)};actions.querySelector('.hs-judge-btn').onclick=e=>{e.stopPropagation();openDecision(name,d.check||card.querySelector('.quick')?.textContent.replace(/^まず見る：?/,'').trim(),d.target||card.querySelector('.targetline')?.textContent.replace(/^相談ライン/,'').trim(),true)};actions.querySelector('.hs-memo-btn').onclick=e=>{e.stopPropagation();openMemoForm(name)};});}
function decorateSearch(){document.querySelectorAll('.v21-resultwrap').forEach(w=>{if(w.dataset.hs315)return;const name=w.querySelector('.name')?.textContent.trim();if(!name)return;w.dataset.hs315='1';const a=document.createElement('div');a.className='hs-search-actions';const g=getGuide(name);a.innerHTML=`${g?'<button class="hs-toolbtn hs-photo-btn" type="button">📷 見る場所</button>':''}<button class="hs-toolbtn hs-memo-btn" type="button">＋台メモ</button>`;w.appendChild(a);if(g)a.querySelector('.hs-photo-btn').onclick=()=>openGuide(name);a.querySelector('.hs-memo-btn').onclick=()=>openMemoForm(name);});}
function addVisualGuide(){if(!/visual-guide\.html$/.test(location.pathname)||document.getElementById('hsOwnPhotos'))return;const sec=document.createElement('section');sec.id='hsOwnPhotos';sec.className='hs-visual-section';sec.innerHTML='<div class="v21-sectionhead"><b>実機写真｜見る場所</b><span>自前写真</span></div>'+PHOTO_GUIDES.map(g=>`<article class="hs-visual-card"><img src="${g.photos[0].src}" alt="${esc(g.title)}" loading="lazy"><div class="txt"><b>${esc(g.title)}</b><p>${esc(g.photos[0].caption)}</p><button type="button" class="hs-toolbtn" data-guide="${esc(g.title)}" style="margin-top:8px">見る場所を開く</button></div></article>`).join('');const main=document.querySelector('main')||document.body;main.prepend(sec);sec.querySelectorAll('[data-guide]').forEach(b=>b.onclick=()=>openGuide(b.dataset.guide));}

function getRateVisibility(){try{const v=JSON.parse(localStorage.getItem(LS_RATE_VIS)||'null');if(v&&typeof v.normal==='boolean'&&typeof v.low==='boolean')return{normal:v.normal,low:v.low}}catch(e){}return{normal:true,low:true}}
function updateRateVisibilityUI(v){document.body.classList.remove('hs-view-low','hs-view-edge','hs-view-all','hs-low-only');document.body.classList.toggle('hs-hide-normal',!v.normal);document.body.classList.toggle('hs-hide-low',!v.low);document.querySelectorAll('.hs-ratevis-btn').forEach(b=>{const k=b.dataset.ratevis,on=!!v[k];b.classList.toggle('on',on);b.setAttribute('aria-pressed',String(on));const st=b.querySelector('span');if(st)st.textContent=on?'表示中':'非表示'});const empty=document.getElementById('hsRateEmpty');if(empty)empty.hidden=v.normal||v.low}
function setRateVisibility(v,save=true){const next={normal:v?.normal!==false,low:v?.low!==false};if(save)try{localStorage.setItem(LS_RATE_VIS,JSON.stringify(next))}catch(e){}updateRateVisibilityUI(next);document.dispatchEvent(new CustomEvent('hallscan-ratechange',{detail:next}));try{if(/search\.html$/.test(location.pathname)&&typeof render==='function')render()}catch(e){}}
function toggleRateVisibility(kind){const v=getRateVisibility();v[kind]=!v[kind];setRateVisibility(v)}
function addRateVisibilityBar(){const fn=location.pathname.split('/').pop()||'index.html';if(!(/search\.html$/.test(fn)||/stores\.html$/.test(fn)||/abashiri\.html$/.test(fn)||/_integrated_factchecked\.html$/.test(fn)))return;if(document.getElementById('hsRateVisBar'))return;const bar=document.createElement('section');bar.id='hsRateVisBar';bar.className='hs-ratevisbar';bar.innerHTML='<div class="hs-ratevis-copy"><b>レート表示</b><small>両方ONが通常表示</small></div><div class="hs-ratevis-segments" role="group" aria-label="表示する貸玉レート"><button type="button" class="hs-ratevis-btn" data-ratevis="normal"><b>通常レート</b><span>表示中</span></button><button type="button" class="hs-ratevis-btn" data-ratevis="low"><b>低貸</b><span>表示中</span></button></div><div id="hsRateEmpty" class="hs-ratevis-empty" hidden>通常レートと低貸が両方とも非表示です。上のボタンから表示するレートを選んでください。</div>';const header=document.querySelector('header');if(header)header.insertAdjacentElement('afterend',bar);else document.body.prepend(bar);bar.querySelectorAll('.hs-ratevis-btn').forEach(b=>b.onclick=()=>toggleRateVisibility(b.dataset.ratevis));updateRateVisibilityUI(getRateVisibility())}
function tagLowRateContent(){const fn=location.pathname.split('/').pop()||'';const isStore=/abashiri\.html$/.test(fn)||/_integrated_factchecked\.html$/.test(fn);if(isStore){const main=document.querySelector('main');if(main)[...main.children].forEach(el=>{if(!el.classList.contains('v311-help'))el.classList.add('hs-lowrate-content')});if(/abashiri\.html$/.test(fn)){document.querySelector('header input#search')?.classList.add('hs-lowrate-content')}else{document.querySelectorAll('header .sub,header .mode,header .search,header .filters').forEach(el=>el.classList.add('hs-lowrate-content'))}}if(/stores\.html$/.test(fn))document.querySelectorAll('.v21-storerow>div:nth-child(2)>span').forEach(el=>el.classList.add('hs-lowrate-label'))}
function normalFavKey(file,kind,rate,name){return `normal|${file}|${kind}|${rate}|${name}`}
function loadSharedFavs(){try{return new Set(JSON.parse(localStorage.getItem(NORMAL_FAV_KEY)||'[]'))}catch(e){return new Set}}
function saveSharedFavs(set){try{localStorage.setItem(NORMAL_FAV_KEY,JSON.stringify([...set]))}catch(e){}}
function currentStoreData(){const all=FULLRATE(),fn=location.pathname.split('/').pop()||'';if(fn==='abashiri.html'){const s=new URLSearchParams(location.search).get('store');return all['abashiri:'+s]||null}for(const d of Object.values(all)){if((d.file||'').split('?')[0]===fn)return d}return null}
function sourceLink(s){const u=s?.source||'',b=s?.benefitSource||'';const links=[];if(/^https?:\/\//.test(u)){const label=sourceNeedsWeb(s)?'設置確認元を開く ↗':'参照元を開く ↗';links.push(`<a class="hs-source-link" href="${esc(u)}" target="_blank" rel="noopener">${label}</a>`)}if(/^https?:\/\//.test(b)&&b!==u)links.push(`<a class="hs-source-link" href="${esc(b)}" target="_blank" rel="noopener">天井・出玉元を開く ↗</a>`);return links.join(' ')}
function detailField(label,val){if(!val||val==='—')return'';return `<div class="hs-strategy-field"><b>${esc(label)}</b><p>${esc(beginnerStrategyText(val))}</p></div>`}
function strategyCard(d,kind,rate,name,sharedFavs){const s=strategyFor(name),st=statusInfo(s),fk=normalFavKey(d.file,kind,rate,name),on=sharedFavs.has(fk),eligible=!!s.edge,target=storeTargetForDisplay(s,d,kind);return `<details class="hs-strategy-card hs-type-${st.cls}" data-edge="${eligible?'1':'0'}"><summary><div class="hs-strategy-main"><div class="hs-strategy-title">${esc(name)}</div><div class="hs-strategy-quick"><span>相談ライン</span>${esc(target)}</div></div><div class="hs-strategy-side"><span class="hs-rate-chip">${esc(rate)}</span><span class="hs-status hs-status-${st.cls}">${esc(st.label)}</span><button type="button" class="hs-normal-fav${on?' on':''}" data-key="${esc(fk)}" aria-label="${on?'お気に入り解除':'お気に入り追加'}" aria-pressed="${on}">${on?'★':'☆'}</button></div></summary><div class="hs-strategy-detail">${detailField('まず見る',s.check)}${detailField('相談ライン',target)}${detailField(kind==='pachi'?'遊タイム・条件':'天井・条件',s.ceiling)}${detailField(kind==='pachi'?'到達時の恩恵':'天井到達時の恩恵',s.benefit)}${detailField('最低保証・注意',s.minimum)}${detailField(kind==='pachi'?'初期玉数・構造':'初期枚数・AT構造',s.initial)}${detailField('平均獲得目安',s.average)}${detailField('短縮・数え方',s.short)}${detailField('やめる目安',s.stop)}${detailField('注意',s.note)}${sourceCaution(s)}<div class="hs-strategy-foot"><span class="${freshnessClass(s.checked).trim()}">${esc(freshnessText(s.checked,'攻略確認'))}</span>${sourceLink(s)}</div><div class="hs-strategy-actions">${eligible?'<button type="button" class="hs-toolbtn hs-normal-judge">A/B/C/D判定</button>':''}<button type="button" class="hs-toolbtn hs-normal-memo">＋台メモ</button></div></div></details>`}
function injectFullRateSection(){const d=currentStoreData();if(!d||document.getElementById('hsFullRate'))return;const main=document.querySelector('main');if(!main)return;const sec=document.createElement('section');sec.id='hsFullRate';sec.className='hs-fullrate-section';const modes=[];if(d.pachi4?.length)modes.push(['pachi','4パチ',d.pachiLabel,d.pachi4]);if(d.slot20?.length)modes.push(['slot','20スロ',d.slotLabel,d.slot20]);if(!modes.length){sec.innerHTML=`<div class="hs-fullrate-head"><b>通常レート</b><small class="${freshnessClass(d.checked).trim()}">${esc(freshnessText(d.checked,'設置確認'))}｜4パチ・20スロ掲載なし</small></div><div class="hs-fullrate-empty">現在の店舗掲載では通常レートを確認できません。</div>`;main.appendChild(sec);return}let mode=modes[0][0],limit=60;let sharedFavs=loadSharedFavs();sec.innerHTML=`<div class="hs-fullrate-head"><b>通常レート｜${esc(d.store||'実戦情報')}</b><small class="${freshnessClass(d.checked).trim()}">${esc(freshnessText(d.checked,'設置確認'))}${d.sourceUpdated?'｜P-WORLD更新 '+esc(d.sourceUpdated):''}　${esc(freshnessText(STRATEGY().checked||STRATEGY_CHECKED,'攻略確認'))}</small><p>「期待値候補」は相談ラインです。条件達成だけで座らず、A/B/C/D判定を受けてください。<br><b>交換表記：</b>「交換ロスなし」＝借りた時と交換時のメダル価値が同じ。「56枚=1000円交換」＝景品1000円分に56枚必要。交換率不明ならチャットで確認。${storeExchangeNote(d)?`<br><b>この店舗：</b>${esc(storeExchangeNote(d))}`:''}</p></div><div class="hs-rate-tabs">${modes.map(x=>`<button type="button" class="hs-rate-tab${x[0]===mode?' on':''}" data-mode="${x[0]}">${x[1]} ${x[3].length}</button>`).join('')}</div><div class="hs-fullrate-searchwrap"><input class="hs-fullrate-search" type="search" placeholder="通常レートの機種名を検索" aria-label="通常レート設置機種を検索"></div><div class="hs-fullrate-count"></div><div class="hs-fullrate-list"></div><button type="button" class="hs-fullrate-more">続きを表示</button>`;main.appendChild(sec);const inp=sec.querySelector('.hs-fullrate-search'),list=sec.querySelector('.hs-fullrate-list'),cnt=sec.querySelector('.hs-fullrate-count'),more=sec.querySelector('.hs-fullrate-more');function getRows(){const x=modes.find(z=>z[0]===mode)||modes[0],raw=inp.value.trim();let arr=x[3].map(n=>({name:n,s:strategyFor(n)}));if(raw)arr=arr.filter(o=>searchScore({name:o.name,store:d.store,quick:o.s.check,target:o.s.target,rate:x[2],strategy:o.s},raw)>0);return{x,arr}}
 function draw(){const{x,arr}=getRows(),shown=arr.slice(0,limit),edgeCount=x[3].filter(n=>strategyFor(n).edge).length;cnt.innerHTML=`<span>${esc(x[2])}</span><span>全${x[3].length} / 候補${edgeCount}</span>`;list.innerHTML=shown.map(o=>strategyCard(d,x[0],x[2],o.name,sharedFavs)).join('')||'<div class="hs-fullrate-empty">該当する設置機種はありません。</div>';more.hidden=shown.length>=arr.length;more.textContent=`続きを表示（残り ${Math.max(0,arr.length-shown.length)}）`;list.querySelectorAll('.hs-normal-fav').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const fk=b.dataset.key;sharedFavs.has(fk)?sharedFavs.delete(fk):sharedFavs.add(fk);saveSharedFavs(sharedFavs);draw()});list.querySelectorAll('.hs-normal-judge').forEach(b=>b.onclick=e=>{e.preventDefault();const det=b.closest('.hs-strategy-card'),name=det.querySelector('.hs-strategy-title')?.textContent||'',s=strategyFor(name);openDecision(name,s.check,storeTargetForDisplay(s,d,x[0]),!!s.edge,sourceNeedsWeb(s))});list.querySelectorAll('.hs-normal-memo').forEach(b=>b.onclick=e=>{e.preventDefault();const name=b.closest('.hs-strategy-card')?.querySelector('.hs-strategy-title')?.textContent||'';openMemoForm(name)});}
 sec.querySelectorAll('.hs-rate-tab').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;limit=60;sec.querySelectorAll('.hs-rate-tab').forEach(x=>x.classList.toggle('on',x===b));draw()});inp.addEventListener('input',()=>{limit=60;draw()});more.onclick=()=>{limit+=80;draw()};document.addEventListener('hallscan-ratechange',draw);const qp=new URLSearchParams(location.search).get('q');if(qp){const hitP=d.pachi4?.some(x=>searchScore({name:x,store:d.store,quick:strategyFor(x).check,target:strategyFor(x).target,rate:d.pachiLabel},qp)>0),hitS=d.slot20?.some(x=>searchScore({name:x,store:d.store,quick:strategyFor(x).check,target:strategyFor(x).target,rate:d.slotLabel},qp)>0);if(hitS&&!hitP)mode='slot';inp.value=qp;sec.querySelectorAll('.hs-rate-tab').forEach(b=>b.classList.toggle('on',b.dataset.mode===mode))}draw();}
function addStoreNormalCounts(){if(!/stores\.html$/.test(location.pathname))return;const all=FULLRATE();document.querySelectorAll('.v21-storerow').forEach(row=>{if(row.querySelector('.hs-store-normal'))return;let d=null;const href=row.getAttribute('href')||'';if(/abashiri\.html/.test(href)){const s=new URL(href,location.href).searchParams.get('store');d=all['abashiri:'+s]}else{const fn=href.split('/').pop().split('?')[0];d=Object.values(all).find(x=>(x.file||'').split('?')[0]===fn)}if(!d)return;const box=document.createElement('div');box.className='hs-store-normal';const p=d.pachi4?.length||0,sl=d.slot20?.length||0,pe=(d.pachi4||[]).filter(n=>strategyFor(n).edge).length,se=(d.slot20||[]).filter(n=>strategyFor(n).edge).length;box.dataset.p=p;box.dataset.s=sl;box.dataset.pe=pe;box.dataset.se=se;const txt=row.querySelector('div:nth-child(2)');if(txt)txt.appendChild(box)});function redraw(){document.querySelectorAll('.hs-store-normal').forEach(box=>{const p=+box.dataset.p,s=+box.dataset.s,pe=+box.dataset.pe,se=+box.dataset.se,bits=[];if(p)bits.push(`<span class="hs-rate-chip">4パチ ${p} / 候補${pe}</span>`);if(s)bits.push(`<span class="hs-rate-chip">20スロ ${s} / 候補${se}</span>`);box.innerHTML=bits.join('')||'<span class="hs-unranked">通常レートなし</span>'})}redraw();document.addEventListener('hallscan-ratechange',redraw);}

const SEARCH_ALIASES={'東京ぐーる':'東京喰種','とうきょうぐーる':'東京喰種','ぐーる':'東京喰種','tokyoghoul':'東京喰種','りぜろ':'ゼロから始める異世界生活','もんきー':'モンキーターン','乙女4':'戦国乙女4','おとめ4':'戦国乙女4','乙女5':'戦国乙女5','おとめ5':'戦国乙女5','すますろ北斗':'スマスロ北斗の拳','すますろほくと':'スマスロ北斗の拳','かばねり':'甲鉄城のカバネリ','ごっどいーたー':'ゴッドイーター','からくり':'からくりサーカス','炎炎':'炎炎ノ消防隊','えんえん':'炎炎ノ消防隊','ヴヴヴ':'革命機ヴァルヴレイヴ','ゔゔゔ':'革命機ヴァルヴレイヴ','ばるぶれいぶ':'革命機ヴァルヴレイヴ','sao':'ソードアートオンライン','まどまぎ':'魔法少女まどかマギカ','えゔぁ':'エヴァンゲリオン','禁書':'とある魔術の禁書目録','きんしょ':'とある魔術の禁書目録','れーるがん':'とある科学の超電磁砲','りこりこ':'リコリスリコイル','じゃぐ':'ジャグラー'};
function lev(a,b){const n=a.length,m=b.length;if(Math.abs(n-m)>2)return 99;let prev=Array.from({length:m+1},(_,i)=>i);for(let i=1;i<=n;i++){const cur=[i];let rowMin=i;for(let j=1;j<=m;j++){cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));rowMin=Math.min(rowMin,cur[j])}if(rowMin>2)return 99;prev=cur}return prev[m]}
function aliasTerm(q){const n=normLite(q),rows=Object.entries(SEARCH_ALIASES).map(([a,c])=>[normLite(a),normLite(c)]);for(const[a,c]of rows)if(a===n)return c;if(n.length>=4){for(const[a,c]of rows)if(Math.abs(a.length-n.length)<=1&&lev(n,a)<=1)return c}return n}
function fuzzyOneEdit(q,n){if(q.length<4||!n)return false;if(lev(q,n)<=1)return true;for(let l=Math.max(1,q.length-1);l<=q.length+1;l++)for(let i=0;i+l<=n.length;i++)if(lev(q,n.slice(i,i+l))<=1)return true;return false}
function dice(a,b){if(a.length<2||b.length<2)return a===b?1:0;const A=[],B=[];for(let i=0;i<a.length-1;i++)A.push(a.slice(i,i+2));for(let i=0;i<b.length-1;i++)B.push(b.slice(i,i+2));let hit=0,used=new Set;for(const x of A){const j=B.findIndex((y,i)=>y===x&&!used.has(i));if(j>=0){used.add(j);hit++}}return 2*hit/(A.length+B.length)}
function searchScore(x,raw){const q=normLite(raw);if(!q)return 1;const canon=aliasTerm(raw),name=normLite(x.name),hay=normLite([x.name,x.store,x.quick,x.target,x.rate,x.strategy?.ceiling,x.strategy?.benefit,x.strategy?.minimum,x.strategy?.initial,x.strategy?.average,x.strategy?.note].join(' '));if(name===q)return 1000;if(canon!==q&&name===canon)return 980;if(canon!==q&&name.startsWith(canon))return 950;if(canon!==q&&name.includes(canon))return 930;if(name.startsWith(q))return 910;if(name.includes(q))return 880;if(hay.includes(q)||hay.includes(canon))return 780;const f=canon!==q?canon:q;if(f.length>=4&&fuzzyOneEdit(f,name))return 680;if(f.length>=4&&dice(f,name)>=.72)return 620;return 0}
function normalSearchRows(){const out=[];for(const d of Object.values(FULLRATE())){for(const n of(d.pachi4||[])){const s=strategyFor(n);out.push({area:d.area,store:d.store,file:d.file,kind:'pachi',rank:'',name:n,quick:s.check,target:s.target,rate:d.pachiLabel,normalRate:true,checked:d.checked,strategy:s})}for(const n of(d.slot20||[])){const s=strategyFor(n);out.push({area:d.area,store:d.store,file:d.file,kind:'slot',rank:'',name:n,quick:s.check,target:s.target,rate:d.slotLabel,normalRate:true,checked:d.checked,strategy:s})}}return out}
function installEnhancedSearch(){if(!/search\.html$/.test(location.pathname))return;try{if(typeof DATA==='undefined'||typeof render!=='function')return}catch(e){return}const normals=normalSearchRows(),low=DATA,rr={S:0,A:1,B:2,C:3,D:4},oldKey=key;function k2(x){return x.normalRate?normalFavKey(x.file,x.kind,x.rate,x.name):oldKey(x)}function priority(x){if(!x.normalRate)return rr[x.rank]??4;const t=x.strategy?.type;return x.strategy?.edge?5:t==='setting'?6:t==='no-g'?7:8}render=function(){const raw=q.value.trim(),vis=getRateVisibility(),normalPool=vis.normal?normals:[],lowPool=vis.low?low:[],all=lowPool.concat(normalPool),a=all.map(x=>({x,score:searchScore(x,raw)})).filter(o=>{const x=o.x;if(filter==='slot'&&x.kind!=='slot')return false;if(filter==='pachi'&&x.kind!=='pachi')return false;if(filter==='abashiri'&&x.area!=='網走')return false;if(filter==='kitami'&&x.area!=='北見')return false;if(filter==='fav'&&!favs.has(k2(x)))return false;return !raw||o.score>0}).sort((a,b)=>raw?(b.score-a.score)||priority(a.x)-priority(b.x)||a.x.name.localeCompare(b.x.name,'ja'):priority(a.x)-priority(b.x)||a.x.name.localeCompare(b.x.name,'ja')).map(o=>o.x);const limit=raw?320:120;count.textContent=a.length+'件'+(a.length>limit?'（先頭'+limit+'件表示）':'');const shown=a.slice(0,limit);root.innerHTML=shown.map(x=>{const href='./'+x.file+(x.file.includes('?')?'&':'?')+'q='+encodeURIComponent(x.name),k=k2(x),on=favs.has(k),img=typeof machineImage==='function'?machineImage(x.name):'',s=x.strategy,st=x.normalRate?statusInfo(s):null,label=x.normalRate?(s?.edge?'相談ライン':s?.type==='setting'?'狙い方':s?.type==='no-g'?'G数狙い':'状態'):'相談ライン',meta=x.normalRate?` · ${esc(x.rate||'')} · ${esc(st.label)}`:'';return `<div class="v21-resultwrap${x.normalRate?' hs-search-normal hs-type-'+st.cls:''}"><a class="v21-result" href="${href}">${img?`<div class="v32-machineThumb"><img src="${img}" alt="${esc(x.name)}の筐体" loading="lazy" width="96" height="128" onerror="this.closest('.v32-machineThumb').classList.add('is-broken');this.remove()"></div>`:`<div class="v21-rank ${esc(x.rank)}">${esc(x.rank||(x.normalRate?'通':'—'))}</div>`}<div><div class="name">${esc(x.name)}</div><div class="meta">${esc(x.area)} · ${esc(x.store)}${meta}</div><div class="quick"><span class="v23-target-label">${esc(label)}</span>${esc(x.normalRate?targetForDisplay(s):(x.target||x.quick))}</div></div><div class="chev">›</div></a><button class="v21-fav ${on?'on':''}" type="button" data-key="${esc(k)}" aria-label="${on?'お気に入り解除':'お気に入り追加'}" aria-pressed="${on}">${on?'★':'☆'}</button></div>`}).join('');empty.textContent=(!getRateVisibility().normal&&!getRateVisibility().low)?'通常レートと低貸が両方とも非表示です。':filter==='fav'?'現在表示中のレートにお気に入りはありません。':'該当する機種がありません。';empty.style.display=a.length?'none':'block';document.querySelectorAll('.v21-fav').forEach(b=>b.onclick=()=>{const kk=b.dataset.key;favs.has(kk)?favs.delete(kk):favs.add(kk);saveFavs();render()});decorateSearch();replaceConsultationLabels(root)};render();}

function clarifyPriorityUI(root=document.body){if(!root)return;root.querySelectorAll('.rank,.v21-rank').forEach(el=>{if(el.dataset.hsPriorityApplied==='1')return;const r=(el.dataset.hsPriority||el.textContent||'').trim();if(!/^[SABCDX]$/.test(r))return;el.dataset.hsPriority=r;el.dataset.hsPriorityApplied='1';el.textContent='巡回 '+r;el.classList.add('hs-priority-rank');el.setAttribute('aria-label',`巡回優先度 ${r}。A/B/C/D判定とは別です`);const a=el.closest('.v21-result');if(a)a.classList.add('hs-has-priority')});root.querySelectorAll('button[data-rank],button[data-r]').forEach(b=>{if(b.dataset.hsPriorityApplied==='1')return;const r=b.dataset.rank||b.dataset.r;if(/^[SABCDX]$/.test(r)){b.dataset.hsPriorityApplied='1';b.textContent='優先度 '+r;b.setAttribute('aria-label',`巡回優先度 ${r}で絞り込み`)}});root.querySelectorAll('.kpi span').forEach(el=>{if(el.textContent==='Sランク')el.textContent='巡回S';if(el.textContent==='Aランク')el.textContent='巡回A'});root.querySelectorAll('.sectionnote').forEach(el=>{if(/S＝最優先/.test(el.textContent)&&!el.dataset.hsPriorityNote){el.dataset.hsPriorityNote='1';el.textContent=el.textContent.replace('S＝最優先、A＝有力、B以下＝条件付き。','巡回優先度：S＝最優先、A＝有力、B以下＝条件付き。A/B/C/Dの最終判定とは別です。')}});root.querySelectorAll('h2').forEach(el=>{if(/^巡回優先（S\/A）/.test(el.textContent))el.childNodes[0].nodeValue='巡回優先度（S/A） '})}
function annotateStaticFreshness(root=document.body){if(!root)return;root.querySelectorAll('.eyebrow,header .sub').forEach(el=>{if(el.dataset.hsFresh)return;const m=el.textContent.match(/(20\d{2}-\d{2}-\d{2})/);if(!m)return;el.dataset.hsFresh='1';const n=daysSince(m[1]);if(n!==null){el.textContent=el.textContent.replace(m[1],`${m[1]}時点・${n===0?'今日':n+'日前確認'}${n>=7?'・要再確認':''}`);if(n>=7)el.classList.add('hs-stale')}})}
function init(){replaceConsultationLabels();tagLowRateContent();addRateVisibilityBar();addPatrolToggle();updateMemoFab();decorateCards();decorateSearch();addVisualGuide();injectFullRateSection();addStoreNormalCounts();installEnhancedSearch();setRateVisibility(getRateVisibility(),false);clarifyPriorityUI();annotateStaticFreshness();const mo=new MutationObserver(()=>{decorateCards();decorateSearch();clarifyPriorityUI();annotateStaticFreshness()});mo.observe(document.body,{childList:true,subtree:true});}
init();
})();
