(()=>{
'use strict';
const VER='v3.13', CHECKED='2026-09-18';
const LS_PATROL='hallscan_patrol_v1', LS_MEMO='hallscan_found_memos_v1';
const PHOTO_GUIDES=[
 {re:/モンキーターンV/,title:'モンキーターンV',photos:[
  {src:'./hallscan-monkey-main.webp',caption:'メイン液晶。右上のpt表示を確認。',markers:[{x:88,y:14,t:'pt'}]},
  {src:'./hallscan-monkey-side.webp',caption:'サブ液晶。メニュー・履歴などを確認する位置。',markers:[{x:52,y:20,t:'サブ液晶'}]}
 ]},
 {re:/戦国乙女4/,title:'戦国乙女4',photos:[
  {src:'./hallscan-otome-main.webp',caption:'筐体正面。左側G数と右側サブ表示の位置を把握。',markers:[{x:9,y:59,t:'G数'},{x:90,y:58,t:'サブ'}]},
  {src:'./hallscan-otome-side.webp',caption:'右側サブ表示のアップ。数値を確認する場所。',markers:[{x:56,y:27,t:'ここ'}]}
 ]}
];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});
function getGuide(name){return PHOTO_GUIDES.find(x=>x.re.test(name||''));}
function storeName(){return document.querySelector('header h1')?.textContent.trim()||document.title.replace(/\s*[｜|].*$/,'');}
function getMemos(){try{return JSON.parse(localStorage.getItem(LS_MEMO)||'[]').filter(x=>x&&x.date===today())}catch(e){return[]}}
function saveMemos(a){try{localStorage.setItem(LS_MEMO,JSON.stringify(a))}catch(e){}}
function modal(){let m=document.getElementById('hsModal');if(m)return m;m=document.createElement('div');m.id='hsModal';m.className='hs-modal';m.innerHTML='<section class="hs-sheet" role="dialog" aria-modal="true"><div class="hs-sheethead"><strong id="hsModalTitle"></strong><button class="hs-close" type="button" aria-label="閉じる">×</button></div><div id="hsModalBody"></div></section>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('.hs-close'))m.classList.remove('open')});return m}
function openModal(title,html){const m=modal();m.querySelector('#hsModalTitle').textContent=title;m.querySelector('#hsModalBody').innerHTML=html;m.classList.add('open');return m}
function guideHtml(g){return `<div class="hs-guideText">写真は実際のホールで撮影した見え方です。数値の意味は機種カードの「まず見る」「座る目安」と合わせて確認してください。</div><div class="hs-photos">${g.photos.map(p=>`<figure class="hs-photo"><img src="${p.src}" alt="${esc(g.title)}の確認場所" loading="eager">${(p.markers||[]).map(m=>`<span class="hs-marker" style="left:${m.x}%;top:${m.y}%">${esc(m.t)}</span>`).join('')}<figcaption class="hs-guideText" style="margin:0;border-radius:0">${esc(p.caption)}</figcaption></figure>`).join('')}</div>`}
function openGuide(name){const g=getGuide(name);if(!g)return;openModal('見る場所｜'+g.title,guideHtml(g))}
function openDecision(name,check,target){const m=openModal('その場判定｜'+name,`<div class="hs-guideText"><b>① まず見る</b><br>${esc(check||'店舗詳細の「まず見る」を確認')}</div><div class="hs-guideText"><b>② 座る目安</b><br>${esc(target||'機種カードの条件を確認')}</div><div class="hs-decisionButtons"><button data-v="yes">条件を満たす</button><button data-v="no">満たさない</button><button data-v="unknown">判別できない</button></div><div id="hsDecisionResult" class="hs-result">上の条件と実機の状態を照合してください。</div>`);m.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const r=m.querySelector('#hsDecisionResult');r.textContent=b.dataset.v==='yes'?'候補：記載された座る目安を満たしています。最終判断は注意点・交換率・予算も確認。':b.dataset.v==='no'?'見送り：現在は記載条件を満たしていません。':'見送り推奨：条件を判別できない状態で推測して打たない。';});}
function openMemoForm(name){const m=openModal('見つけた台をメモ',`<form class="hs-form" id="hsMemoForm"><label>機種<input name="machine" value="${esc(name)}" readonly></label><label>台番号<input name="number" inputmode="numeric" placeholder="例 336"></label><label>現在G・ptなど<input name="state" placeholder="例 510G / 288pt"></label><label>ひとこと<textarea name="note" placeholder="例 CZ3スルー、あとで再確認"></textarea></label><button class="hs-primary" type="submit">今日の候補に保存</button></form>`);m.querySelector('#hsMemoForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),a=getMemos();a.unshift({id:Date.now(),date:today(),store:storeName(),page:location.pathname.split('/').pop(),machine:f.get('machine'),number:f.get('number'),state:f.get('state'),note:f.get('note')});saveMemos(a);m.classList.remove('open');updateMemoFab();};}
function openMemoList(){const a=getMemos(),html=a.length?`<div class="hs-memo-list">${a.map(x=>`<div class="hs-memo-item"><strong>${esc(x.machine)}${x.number?'｜台 '+esc(x.number):''}</strong><small>${esc(x.store)}${x.state?'｜'+esc(x.state):''}${x.note?'<br>'+esc(x.note):''}</small><button type="button" data-del="${x.id}">削除</button></div>`).join('')}</div><button class="hs-toolbtn" style="margin-top:12px" id="hsClearMemos">今日のメモをすべて削除</button>`:'<div class="hs-empty">今日保存した台はありません。</div>';const m=openModal('今日の候補',html);m.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{saveMemos(getMemos().filter(x=>String(x.id)!==b.dataset.del));openMemoList();updateMemoFab()});const c=m.querySelector('#hsClearMemos');if(c)c.onclick=()=>{saveMemos([]);openMemoList();updateMemoFab()};}
function updateMemoFab(){let b=document.getElementById('hsMemoFab');if(!b){b=document.createElement('button');b.id='hsMemoFab';b.className='hs-memo-fab';b.type='button';b.onclick=openMemoList;b.innerHTML='候補メモ <b>0</b>';document.body.appendChild(b)}b.querySelector('b').textContent=getMemos().length;}
function setPatrol(on){document.body.classList.toggle('hs-patrol',on);try{localStorage.setItem(LS_PATROL,on?'1':'0')}catch(e){}document.querySelectorAll('.hs-patrol-toggle').forEach(b=>{b.classList.toggle('on',on);b.setAttribute('aria-pressed',String(on));b.textContent=on?'巡回モード ON':'巡回モード'})}
function addPatrolToggle(){const target=document.querySelector('header')||document.querySelector('.v21-search-head .inner');if(!target||target.querySelector('.hs-patrol-toggle'))return;const wrap=document.createElement('div');wrap.className='hs-tools';wrap.innerHTML='<button type="button" class="hs-toolbtn hs-patrol-toggle">巡回モード</button>';target.appendChild(wrap);wrap.querySelector('button').onclick=()=>setPatrol(!document.body.classList.contains('hs-patrol'));let on=false;try{on=localStorage.getItem(LS_PATROL)==='1'}catch(e){}setPatrol(on)}
function machineData(name){try{if(typeof data!=='undefined'&&Array.isArray(data))return data.find(x=>x.name===name)||{};}catch(e){}return{}}
function decorateCards(){document.querySelectorAll('.card').forEach(card=>{if(card.dataset.hs313)return;const name=card.querySelector('.name')?.textContent.trim();if(!name)return;card.dataset.hs313='1';const d=machineData(name);const actions=document.createElement('div');actions.className='hs-card-actions';const g=getGuide(name);actions.innerHTML=`<span class="hs-checked">確認 9/18</span>${g?'<button class="hs-toolbtn hs-photo-btn" type="button">📷 見る場所</button>':''}<button class="hs-toolbtn hs-judge-btn" type="button">判定</button><button class="hs-toolbtn hs-memo-btn" type="button">＋台メモ</button>`;(card.querySelector('.targetline')||card.querySelector('.quick')||card.querySelector('.head')).after(actions);if(g)actions.querySelector('.hs-photo-btn').onclick=e=>{e.stopPropagation();openGuide(name)};actions.querySelector('.hs-judge-btn').onclick=e=>{e.stopPropagation();openDecision(name,d.check||card.querySelector('.quick')?.textContent.replace(/^まず見る：?/,'').trim(),d.target||card.querySelector('.targetline')?.textContent.replace(/^座る目安/,'').trim())};actions.querySelector('.hs-memo-btn').onclick=e=>{e.stopPropagation();openMemoForm(name)};});}
function decorateSearch(){document.querySelectorAll('.v21-resultwrap').forEach(w=>{if(w.dataset.hs313)return;const name=w.querySelector('.name')?.textContent.trim();if(!name)return;w.dataset.hs313='1';const a=document.createElement('div');a.className='hs-search-actions';const g=getGuide(name);a.innerHTML=`${g?'<button class="hs-toolbtn hs-photo-btn" type="button">📷 見る場所</button>':''}<button class="hs-toolbtn hs-memo-btn" type="button">＋台メモ</button><span class="hs-checked">確認 9/18</span>`;w.appendChild(a);if(g)a.querySelector('.hs-photo-btn').onclick=()=>openGuide(name);a.querySelector('.hs-memo-btn').onclick=()=>openMemoForm(name);});}
function addVisualGuide(){if(!/visual-guide\.html$/.test(location.pathname)||document.getElementById('hsOwnPhotos'))return;const sec=document.createElement('section');sec.id='hsOwnPhotos';sec.className='hs-visual-section';sec.innerHTML='<div class="v21-sectionhead"><b>実機写真｜見る場所</b><span>自前写真</span></div>'+PHOTO_GUIDES.map(g=>`<article class="hs-visual-card"><img src="${g.photos[0].src}" alt="${esc(g.title)}" loading="lazy"><div class="txt"><b>${esc(g.title)}</b><p>${esc(g.photos[0].caption)}</p><button type="button" class="hs-toolbtn" data-guide="${esc(g.title)}" style="margin-top:8px">見る場所を開く</button></div></article>`).join('');const main=document.querySelector('main')||document.body;main.prepend(sec);sec.querySelectorAll('[data-guide]').forEach(b=>b.onclick=()=>openGuide(b.dataset.guide));}
function init(){addPatrolToggle();updateMemoFab();decorateCards();decorateSearch();addVisualGuide();const mo=new MutationObserver(()=>{decorateCards();decorateSearch()});mo.observe(document.body,{childList:true,subtree:true});}
init();
})();
